### ISSUE TITLE
Master List: Implement shortcuts

### ISSUE THREAD

**Issue by charliescheer** [Automattic/simplenote-macos#1143]
As requested in issue #1074 we want to implement macOS shortcuts in Simplenote.  The goal with this project will be to supply feature parity to the iOS shortcuts.

Tasks:

- [x] Add Apps intent extension #1144 
- [x] implement apps intent shortcuts #1145 
- [x] explore siri integrations. #1146

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by charliescheer** [comment]
This project is effectively done.  Close this issue
