### ISSUE TITLE
Magic Links Support

### ISSUE THREAD

**Issue by jleandroperez** [Automattic/simplenote-macos#1182]
### Details:
- [x] Integrate the new Endpoints #1178
- [x] Implement support for the `simplenotemac://` callback URL #1179
- [x] Implement UI support for the Magic Links Flow #1180
- [x] Implement a new UI to be rendered during the Token Exchange Process #1181

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
