### ISSUE TITLE
Magic Links: Switch to Code Authentication

### ISSUE THREAD

**Issue by jleandroperez** [Automattic/simplenote-macos#1187]
### Details:
- [x] Implement macOS Navigation Controller #1193
- [x] Polish NagitationController Animations #1196
- [x] Refactor AuthUI to handle State and Mode Definitions #1195
- [x] Implement a new Code and Password Interfaces #1197
- [x] Ensure if you get rate limited, during login, you may proceed to the Enter Password UI
- [x] Verify the Magic Link Flow is still supported
- [x] Verify the Invalid Token UI is still triggered https://github.com/Automattic/simplenote-macos/pull/1198
- [x] Adjust UI Details https://github.com/Automattic/simplenote-macos/pull/1198
   - [x] Enter Code TextField should probably be readable (since it's easy to miss, and it expires quickly, anyways)
   - [x] Going Back from the Enter Code UI results in the "Enter Email" UI, with your email highlighted
   - [x] Enter password button's textColor doesn't match the border
   - [x] Enter Password UI needs a header, too, with the account's email (recently added in iOS).
- [x] Update Error Handling: Invalid and Expired Code Errors
- [x] Fix weird back button animation
- [x] Animate Window Resize

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
