### ISSUE TITLE
Master Issue: Advanced Search

### ISSUE THREAD

**Issue by jleandroperez** [Automattic/simplenote-macos#626]
### Details:
- [ ] `tag:` operator support
- [ ] Sort Mode dropdown
- [ ] Intermix Tags / Notes results

### Mockups
<img width="300" src="https://user-images.githubusercontent.com/1195260/89207209-c7a97580-d590-11ea-91ff-8722040b380b.png">
<img width="300" src="https://user-images.githubusercontent.com/1195260/89207218-cb3cfc80-d590-11ea-9899-4d2f2a6cd5cc.png"?
<img width="300" src="https://user-images.githubusercontent.com/1195260/89207222-cc6e2980-d590-11ea-809a-8443139f9d42.png">

**Comment by riverLethe9** [comment]
Issue #33  

How is the addition of 'sort by: date created' going?

**Comment by jleandroperez** [comment]
@riverLethe9 We'll be implementing a new sort bar (which will allow you to sort search results), but no specific ETA at the moment. This particular project will ship early 2021.

Thank you for reaching out!

**Comment by mokagio** [comment]
Bumped this to the 2.11 milestone because there are some tasks are still unchecked and today I'm running the 2.10 code freeze.
