### ISSUE TITLE
Interlinking

### ISSUE THREAD

**Issue by jleandroperez** [Automattic/simplenote-macos#663]
### Tasks:
- [x] New **Copy Internal Link** Editor Action
- [x] New **Copy Internal Link** List Action
- [x] Interlinks should always get linkified
- [x] Clicking over an Internal Link should push the Target Note onscreen
- [x] Markdown Preview Interlink Support
- [x] Markdown Preview Highlight Colors
- [x] Inline Lookup Mechanism
- [ ] References UI

### Inline Lookup Mechanism
- Filtering Mechanism
  - [x] Backgrounding
  - [x] Invalidate previous search OPs
  - [x] Not Deleted
- Geometry
  - [x] Display below the keyword's first character!
  - [x] Prevent horizontal clipping (Screen Overflow)
  - [x] Prevent vertical clipping (Fullscreen)
  - [x] Relocate on Multiline?
- Interface
  - [x] Rounded Corners
  - [x] Cursor = Hand!
- Display / Hide Mechanism
  - [x] Dismiss when there are no keywords
  - [x] Dismiss on: [.mouseClick, .scrollWheel]
  - [x] Allow circular references
- User Input
  - [x] Review: Architecture. NSWindowController Ownership
  - [x] Arrows
  - [x] Interlink Insertion
- Phase II
  - [x] Display only when there are search results
  - [x] Dismiss when there are no results
  - [x] Discard notes that don't contain the keyword in the title
  - [x] BUG: Delete > Ctrl Z > Might result in AutocompleteWindow and incorrect cursor location. Main hook: KeyDown?
  - [x] Review Remote Update Scenarios
  - [x] Review performance in large accounts
  - [ ] Adapt window size to Content!
  - [ ] Display up to 5 autocomplete rows

### Mockups:
![blueprint_macos](https://user-images.githubusercontent.com/1195260/91873978-0e51c480-ec50-11ea-9e80-fadd44f6567a.png)
