### ISSUE TITLE
Email Verification

### ISSUE THREAD

**Issue by jleandroperez** [Automattic/simplenote-macos#800]
### Details
- [x] Simperium Support to sync current Verification State #801
- [x] New “Review You Account” screen #807
- [x] New “Verify Your Email” screen #807
- [x] Display Modal Alert on Error #807
- [x] Open `app.simplenote.com/settings` in a browser if user clicks on “Change Email” #807
- [x] Show “Review You Account” on app launch if user is not verified and verification was not requested #810
- [x] Show “Verify Your Email” on app launch if verification was requested but not completed #810
- [x] Invoke the verification endpoint when the user presses `Confirm` on the `Review` / `Verify` screens #807
- [x] Analytics #807

### Mockups
![macOS_Modal (Dark)](https://user-images.githubusercontent.com/1195260/105076958-8d626080-5a6a-11eb-9cd4-e81751dd681c.png)
![macOS_Modal (Light)](https://user-images.githubusercontent.com/1195260/105076976-93f0d800-5a6a-11eb-8a1e-e6ba58c747c0.png)
![macOS_Modal_2 (Light)](https://user-images.githubusercontent.com/1195260/105076979-96533200-5a6a-11eb-9c96-6d8c61efd62a.png)
![macOS_Modal_Error (Light)](https://user-images.githubusercontent.com/1195260/105076985-98b58c00-5a6a-11eb-98fa-faec7f86961a.png)
![macOS_Modal_Error_2 (Light)](https://user-images.githubusercontent.com/1195260/105076991-9a7f4f80-5a6a-11eb-867a-0a0ec199292d.png)

**Comment by pachlava** [comment]
[testing] Verified #807 and #810. Can't directly verify #801 through UI testing
